require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'ReactNativeAppTS' do
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge', # Include this for RN >= 0.47
    'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket', # Needed for debugging
    'RCTAnimation', # Needed for FlatList and animations running on native UI thread
    # Add any other subspecs you want to use in your project
  ]

  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'ReactNativeAppTSTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

pod 'react-native-camera', path: '../node_modules/react-native-camera'

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end
  end

target 'ReactNativeAppTS-tvOS' do
  # Pods for ReactNativeAppTS-tvOS

  target 'ReactNativeAppTS-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
